In [ ]:
import torch

In [2]:
#rand=0에서 1사이의 임의의 숫자 생성.
#2행 3열짜리 텐서 생성.
x=torch.rand(2,3)
print(x)

tensor([[0.3880, 0.7980, 0.1632],
        [0.0286, 0.0409, 0.7718]])


In [4]:
#randn=평균이 0이고 표준편차가 1인 가우시안 정규분포 안에서 랜덤값 생성.
x=torch.randn(2,3)
print(x)

tensor([[ 0.2679, -1.6411,  1.5529],
        [ 0.3121,  0.3427, -1.2390]])


In [6]:
#randint=randint(a,b,size=(c,d)) ab 사이의 랜덤한 자연수 생성.
x=torch.randint(1,4,size=(2,3))
print(x)

tensor([[2, 3, 1],
        [1, 3, 2]])
